### ISSUE TITLE
 v3.0.0-alpha2 的账号配置是和旧的版本不一样吗

### ISSUE THREAD

**Issue by zsanjin-p** [lss233/chatgpt-for-bot-docs#10]
我按旧的配置文档配置 v3.0.0-alpha2 ，qq机器人一直提示我没有配置好账号，配置如：
[poe]
[[poe.accounts]]
p_b = "xxx"

[slack]
[[slack.accounts]]
channel_id = "xxx" # 这里写你获得的 channel_id:Claude 的识别码 
access_token = "zzz" # 这里写前面获得的 access_token

[bard]
[[bard.accounts]]
cookie_content = 'xxx'

**Comment by lss233** [comment]
是不一样的。 V3 要在 WebUI 配。 文档还没有更新。
