### ISSUE TITLE
“accessToken 的有效期为 30 天”

### ISSUE THREAD

**Issue by bobandbrony** [lss233/chatgpt-for-bot-docs#8]
现在只有14天啦~
![image](https://github.com/lss233/chatgpt-for-bot-docs/assets/129247570/c18a24cd-d7d8-4f8c-838a-a20c93beb9c8)

**Comment by lss233** [comment]
可以发个PR过来改下

**Comment by bobandbrony** [comment]
> 可以发个PR过来改下

已提交

**Comment by lss233** [comment]
Thank you!
